Revert deletions

diff --git a/ksail b/ksail
--- a/ksail
+++ b/ksail
@@ -1,4 +1,166 @@
 #!/bin/bash
+# The version of KSail.
+# This value is overridden by the pipeline that creates new releases.
+# It should not be changed from 'dev'.
+VERSION="dev"
+
+# Global Flags: Flags that can be used with any command
+valid_global_flags=(
+  "-h"
+)
+
+function main_run_help_no_arg() {
+  echo "Usage:"
+  echo -e "  ksail ${PURPLE}<command>${WHITE} ${PURPLE}<flag>${WHITE}"
+  echo
+  echo "Commands:"
+  echo "  install     install dependencies"
+  echo "  up          create cluster"
+  echo "  down        destroy cluster"
+  echo "  update      update cluster (⚠️ unstable)"
+  echo "  validate    validate manifest files (⚠️ unstable)"
+  echo "  verify      verify cluster reconciliation (⚠️ unstable)"
+  echo
+  echo Flags:
+  echo "  -v          print version information"
+  echo
+  echo "Global Flags:"
+  echo "  -h          print help information"
+}
+
+function main_run_help_install_arg() {
+  echo "Usage:"
+  echo "  ksail install <backend>"
+  echo
+  echo "Backends:"
+  echo "  k3d         k3s-in-docker"
+  echo "  talos       talos-in-docker"
+}
+
+function main_run_help_up_arg() {
+  echo "Usage:"
+  echo -e "  ksail up ${PURPLE}<backend>${WHITE} ${PURPLE}[flags]${WHITE}"
+  echo
+  echo "Backends:"
+  echo "  k3d    k3s-in-docker"
+  echo "  talos  talos-in-docker"
+  echo
+  echo "Flags:"
+  echo -e "  -n   name of the cluster (${GREEN}ksail${WHITE})"
+  echo -e "  -m   path to the manifests files that should be pushed to a local OCI registry (${GREEN}./k8s${WHITE})"
+  echo -e "  -f   path to the flux kustomization files within the OCI registry (${GREEN}./clusters/${PURPLE}<cluster-name>${GREEN}/flux${WHITE})"
+  echo
+  echo "ℹ️ Notes:"
+  echo -e "  - Backends may have additional flags. Run '${BLUE}ksail up ${PURPLE}<backend>${BLUE} -h${WHITE}' for more information."
+}
+
+function main_run_help_up_k3d_arg() {
+  echo "Usage:"
+  echo -e " ksail up k3d ${PURPLE}[flags]${WHITE}"
+  echo
+  echo "Flags:"
+  echo -e "  -n   name of the cluster (${GREEN}ksail${WHITE})"
+  echo -e "  -m   path to the manifests files that should be pushed to a local OCI registry (${GREEN}./k8s${WHITE})"
+  echo -e "  -f   path to the flux kustomization files within the OCI registry (${GREEN}./clusters/${PURPLE}<cluster-name>${GREEN}/flux${WHITE})"
+  echo -e "  -c   path to the k3d cluster config file. Configurations in this file will take precedence over other flags."
+}
+
+function main_run_help_up_talos_arg() {
+  echo "Usage:"
+  echo -e " ksail up talos ${PURPLE}[flags]${WHITE}"
+  echo
+  echo "Flags:"
+  echo -e "  -n   name of the cluster (${GREEN}ksail${WHITE})"
+  echo -e "  -m   path to the manifests files that should be pushed to a local OCI registry (${GREEN}./k8s${WHITE})"
+  echo -e "  -f   path to the flux kustomization files within the OCI registry (${GREEN}./clusters/${PURPLE}<cluster-name>${GREEN}/flux${WHITE})"
+}
+
+function main_run_help_down_arg() {
+  echo "Usage:"
+  echo -e "  ksail down ${PURPLE}<backend>${WHITE} ${PURPLE}[flags]${WHITE}"
+  echo
+  echo "Backends:"
+  echo "  k3d    k3s-in-docker"
+  echo "  talos  talos-in-docker"
+  echo
+  echo "Flags:"
+  echo -e "  -n     name of the cluster (${GREEN}ksail${WHITE})"
+}
+
+function main_check_os() {
+  if [[ "$OSTYPE" != "darwin"* && "$OSTYPE" != "linux-gnu"* ]]; then
+    echo "🚫 Unsupported OS. KSail only supports Unix and Linux based operating systems. Exiting..."
+    exit 1
+  fi
+}
+
+function main_define_colors() {
+  RED='\033[1;31m'    # For errors
+  GREEN='\033[1;32m'  # For defaults
+  YELLOW='\033[1;33m' # For warnings
+  BLUE='\033[1;34m'   # For titles
+  PURPLE='\033[1;35m' # For code
+  WHITE='\033[0m'     # For normal text
+}
+
+function main_define_font_types() {
+  NORMAL=$(tput sgr0)    # For normal text
+  BOLD=$(tput bold)      # For prompts and titles
+  ITALIC=$(tput sitm)    # For emphasis
+  UNDERLINE=$(tput smul) # For emphasis
+}
+
+function main_run_global_flags() {
+  local flag=$1
+  local help_arg=$2
+  case "${flag}" in
+  h)
+    main_run_help "$help_arg"
+    exit
+    ;;
+  \?)
+    exit 1
+    ;;
+  esac
+}
+
+function main_run_help() {
+  local help_arg=${1}
+  if [ -z "$help_arg" ]; then
+    main_run_help_no_arg
+  else
+    case $help_arg in
+    install)
+      main_run_help_install_arg
+      exit
+      ;;
+    up)
+      main_run_help_up_arg
+      exit
+      ;;
+    up-k3d)
+      main_run_help_up_k3d_arg
+      exit
+      ;;
+    up-talos)
+      main_run_help_up_talos_arg
+      exit
+      ;;
+    down)
+      main_run_help_down_arg
+      exit
+      ;;
+    *)
+      echo "🚨 Bad help argument: $help_arg"
+      exit 1
+      ;;
+    esac
+  fi
+}
+
+function main_run_version() {
+  echo "KSail $VERSION"
+}
 
 function main_run_down_destroy_k3d_cluster() {
   echo "🔥 Destroying ${cluster_name} cluster"
@@ -43,6 +205,129 @@ function main_run_update() {
     echo "🚨 OCI artifact tag failed. Exiting..."
     exit 1
   }
+}
+
+function main_run_introduction() {
+  echo -e "⛴️ 🐳   ${BOLD}${UNDERLINE}Welcome to ${BLUE}KSail${WHITE}   ⛴️ 🐳${NORMAL}"
+  echo -e "                                     ${BLUE}. . .${WHITE}"
+  echo -e "                __/___                 ${BLUE}:${WHITE}"
+  echo -e "          _____/______|             ___${BLUE}|${WHITE}____     |\"\\/\"|"
+  echo "  _______/_____\_______\_____     ,'        \`.    \  /"
+  echo -e "  \               ${ITALIC}KSail${NORMAL}      |    |  ^        \___/  |"
+  echo -e "${BLUE}~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~${WHITE}"
+  echo
+  echo -e "${BLUE}KSail${WHITE} can help you provision ${GREEN}GitOps enabled K8s environments${WHITE} in ${BLUE}Docker${WHITE}."
+  echo
+}
+
+function main_run_no_arg() {
+
+  main_run_introduction
+  main_run_help
+}
+
+function main_run_install_backend_dependency_homebrew() {
+  if which brew &>/dev/null; then
+    echo "📦✅ Homebrew already installed. Updating..."
+    brew upgrade
+  else
+    echo "📦🔨 Installing Homebrew"
+    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+    if [[ "$OSTYPE" == "darwin"* ]]; then
+      echo "eval '$(/opt/homebrew/bin/brew shellenv)'" >>~/.zprofile
+      eval "$(/opt/homebrew/bin/brew shellenv)"
+    elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
+      echo "eval '$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)'" >>~/.profile
+      eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
+      if $GITHUB_ACTIONS; then
+        # shellcheck disable=SC2086
+        echo "/home/linuxbrew/.linuxbrew/bin" >>$GITHUB_PATH
+      fi
+    fi
+    if ! which brew &>/dev/null; then
+      echo "📦🚨 Homebrew installation failed. Exiting..."
+      exit 1
+    fi
+    echo "📦✅ Homebrew installed"
+  fi
+}
+
+function main_run_install_backend_dependency() {
+  local dependency=${1}
+  local command=${2}
+  if [ -z "$command" ]; then
+    command="$dependency"
+  fi
+  echo "📦 Installing $dependency"
+  if which "$command" &>/dev/null; then
+    echo "📦✅ $dependency already installed. Skipping..."
+  else
+    echo "📦🔨 Installing $dependency"
+    brew install "$dependency"
+    if $GITHUB_ACTIONS; then
+      # shellcheck disable=SC2086
+      which "$command" >>$GITHUB_PATH
+    fi
+    if ! which "$command" &>/dev/null; then
+      echo "📦🚨 $dependency installation failed. Exiting..."
+      exit 1
+    fi
+    echo "📦✅ $dependency installed"
+  fi
+}
+
+function main_run_install_backend_dependencies() {
+  local backend=${1}
+  echo "📦 Installing dependencies"
+  main_run_install_backend_dependency_homebrew
+  main_run_install_backend_dependency "yq"
+  main_run_install_backend_dependency "kubeconform"
+  main_run_install_backend_dependency "kustomize"
+  main_run_install_backend_dependency "docker"
+  main_run_install_backend_dependency "fluxcd/tap/flux" "flux"
+  main_run_install_backend_dependency "gpg"
+  main_run_install_backend_dependency "kubectl"
+  if [[ "$backend" == "k3d" ]]; then
+    main_run_install_backend_dependency "k3d"
+  elif [[ "$backend" == "talos" ]]; then
+    main_run_install_backend_dependency "talos-systems/talos/talosctl" "talosctl"
+  fi
+}
+
+function main_run_install_backend() {
+  if [ $# -gt 2 ]; then
+    echo "🚨 Bad parameters: $*"
+    exit 1
+  fi
+  local command=${2}
+  case $command in
+  k3d)
+    main_run_install_backend_dependencies "k3d"
+    exit
+    ;;
+  talos)
+    main_run_install_backend_dependencies "talos"
+    exit
+    ;;
+  *)
+    if [ $# -eq 2 ]; then
+      local OPTIND=2
+      if getopts "h" flag; then
+        main_run_global_flags "$flag" "install"
+      fi
+    fi
+    echo "🚨 Bad parameters: $*"
+    exit 1
+    ;;
+  esac
+}
+
+function main_run_install() {
+  if [ $# -eq 1 ]; then
+    main_run_help install
+  else
+    main_run_install_backend "$@"
+  fi
 }
 
 function main_run_check_if_docker_is_running() {
@@ -461,3 +746,66 @@ function main_run_down() {
   main_run_down_destroy_cluster "$cluster_name" "$backend"
 
 }
+
+function main_run() {
+  if [ $# -eq 0 ]; then
+    main_run_no_arg
+  else
+    local command=${1}
+    case $command in
+    install)
+      main_run_install "$@"
+      exit
+      ;;
+    up)
+      main_run_up "$@"
+      exit
+      ;;
+    down)
+      main_run_down "$@"
+      exit
+      ;;
+    update)
+      main_run_update "$@"
+      exit
+      ;;
+    validate)
+      main_run_validate "$@"
+      exit
+      ;;
+    verify)
+      main_run_verify "$@"
+      exit
+      ;;
+    *)
+      local OPTIND=1
+      if [ $# -eq 1 ]; then
+        while getopts "hv" flag; do
+          main_run_global_flags "$flag" ""
+          case "${flag}" in
+          v)
+            main_run_version
+            exit
+            ;;
+          *)
+            echo "🚨 Invalid flag: $flag"
+            exit 1
+            ;;
+          esac
+        done
+      fi
+      echo "🚨 Bad parameters: $*"
+      exit 1
+      ;;
+    esac
+  fi
+}
+
+function main() {
+  main_check_os
+  main_define_colors
+  main_define_font_types
+  main_run "$@"
+}
+
+main "$@"
