Refactor test script for ksail command

diff --git a/ksail_test b/ksail_test
--- a/ksail_test
+++ b/ksail_test
@@ -1,132 +1,134 @@
 #!/bin/bash
 
 function test_introduction() {
-  echo -n "🧪 Testing 'ksail'"
+  echo "🧪 Testing 'ksail'"
   ./ksail >/dev/null || {
-    echo "❌"
+    echo "❌ Testing 'ksail' failed"
     exit 1
   }
-  echo "✅"
+  echo "✅ Testing 'ksail' passed"
 }
 
 function test_help_flag() {
-  echo -n "🧪 Testing 'ksail -h'"
+  echo "🧪 Testing 'ksail -h'"
   ./ksail -h >/dev/null || {
-    echo "❌"
+    echo "❌ Testing 'ksail -h' failed"
     exit 1
   }
-  echo "✅"
+  echo "✅ Testing 'ksail -h' passed"
 
-  echo -n "🧪 Testing 'ksail up'"
+  echo "🧪 Testing 'ksail up'"
   ./ksail up >/dev/null || {
-    echo "❌"
+    echo "❌ Testing 'ksail up' failed"
     exit 1
   }
-  echo "✅"
+  echo "✅ Testing 'ksail up' passed"
 
-  echo -n "🧪 Testing 'ksail up -h'"
+  echo "🧪 Testing 'ksail up -h'"
   ./ksail up -h >/dev/null || {
-    echo "❌"
+    echo "❌ Testing 'ksail up -h' failed"
     exit 1
   }
-  echo "✅"
+  echo "✅ Testing 'ksail up -h' passed"
 
-  echo -n "🧪 Testing 'ksail up k3d -h'"
+  echo "🧪 Testing 'ksail up k3d -h'"
   ./ksail up k3d -h >/dev/null || {
-    echo "❌"
+    echo "❌ Testing 'ksail up k3d -h' failed"
     exit 1
   }
-  echo "✅"
+  echo "✅ Testing 'ksail up k3d -h' passed"
 
-  echo -n "🧪 Testing 'ksail up talos -h'"
+  echo "🧪 Testing 'ksail up talos -h'"
   ./ksail up talos -h >/dev/null || {
-    echo "❌"
+    echo "❌ Testing 'ksail up talos -h' failed"
     exit 1
   }
-  echo "✅"
+  echo "✅ Testing 'ksail up talos -h' passed"
 
-  echo -n "🧪 Testing 'ksail down'"
+  echo "🧪 Testing 'ksail down'"
   ./ksail down >/dev/null || {
-    echo "❌"
+    echo "❌ Testing 'ksail down' failed"
     exit 1
   }
-  echo "✅"
+  echo "✅ Testing 'ksail down' passed"
 
-  echo -n "🧪 Testing 'ksail down -h'"
+  echo "🧪 Testing 'ksail down -h'"
   ./ksail down -h >/dev/null || {
-    echo "❌"
+    echo "❌ Testing 'ksail down -h' failed"
     exit 1
   }
-  echo "✅"
+  echo "✅ Testing 'ksail down -h' passed"
 
-  echo -n "🧪 Testing 'ksail down k3d -h'"
+  echo "🧪 Testing 'ksail down k3d -h'"
   ./ksail down k3d -h >/dev/null || {
-    echo "❌"
+    echo "❌ Testing 'ksail down k3d -h' failed"
     exit 1
   }
-  echo "✅"
+  echo "✅ Testing 'ksail down k3d -h' passed"
 
-  echo -n "🧪 Testing 'ksail down talos -h'"
+  echo "🧪 Testing 'ksail down talos -h'"
   ./ksail down talos -h >/dev/null || {
-    echo "❌"
+    echo "❌ Testing 'ksail down talos -h' failed"
     exit 1
   }
-  echo "✅"
+  echo "✅ Testing 'ksail down talos -h' passed"
 
-  echo -n "🧪 Testing 'ksail install'"
+  echo "🧪 Testing 'ksail install'"
   ./ksail install >/dev/null || {
-    echo "❌"
+    echo "❌ Testing 'ksail install' failed"
     exit 1
   }
-  echo "✅"
+  echo "✅ Testing 'ksail install' passed"
 
-  echo -n "🧪 Testing 'ksail install -h'"
+  echo "🧪 Testing 'ksail install -h'"
   ./ksail install -h >/dev/null || {
-    echo "❌"
+    echo "❌ Testing 'ksail install -h' failed"
     exit 1
   }
-  echo "✅"
+  echo "✅ Testing 'ksail install -h' passed"
 }
 
 function test_version_flag() {
-  echo -n "🧪 Testing 'ksail -v'"
+  echo "🧪 Testing 'ksail -v'"
   ./ksail -v >/dev/null || {
-    echo "❌"
+    echo "❌ Testing 'ksail -v' failed"
     exit 1
   }
-  echo "✅"
+  echo "✅ Testing 'ksail -v' passed"
 }
 
 function test_install() {
-  echo -n "🧪 Testing 'ksail install k3d'"
+  echo "🧪 Testing 'ksail install k3d'"
   ./ksail install k3d >/dev/null || {
-    echo "❌"
+    echo "❌ Testing 'ksail install k3d' failed"
     exit 1
   }
-  echo "✅"
+  echo "✅ Testing 'ksail install k3d' passed"
 
-  echo -n "🧪 Testing 'ksail install talos'"
+  echo "🧪 Testing 'ksail install talos'"
   ./ksail install talos >/dev/null || {
-    echo "❌"
+    echo "❌ Testing 'ksail install talos' failed"
     exit 1
   }
-  echo "✅"
+  echo "✅ Testing 'ksail install talos' passed"
 }
 
 function test_up() {
-  echo -n "🧪 Testing 'ksail up k3d -n test'"
-  ./ksail up k3d -n test >/dev/null 2>&1 || {
-    echo "❌"
+  echo "🧪 Testing 'ksail up k3d -n test'"
+  ./ksail up k3d test >/dev/null 2>&1 || {
+    echo "❌ Testing 'ksail up k3d -n test' failed"
     exit 1
   }
+  echo "✅ Testing 'ksail up k3d -n test' passed"
 }
 
 function test_down() {
-  echo -n "🧪 Testing 'ksail down k3d -n test'"
-  ./ksail down k3d -n test >/dev/null 2>&1 || {
-    echo "❌"
+  echo "🧪 Testing 'ksail down k3d -n test'"
+  ./ksail down k3d test >/dev/null 2>&1 || {
+    echo "❌ Testing 'ksail down k3d -n test' failed"
     exit 1
   }
+  echo "✅ Testing 'ksail down k3d -n test' passed"
 }
 
 # Run all the tests
