Add k3d support and alot of cleanup

diff --git a/ksail b/ksail
--- a/ksail
+++ b/ksail
@@ -1,12 +1,23 @@
 #!/bin/bash
-function check_os() {
+
+valid_global_flags=(
+  "-h"
+  "-v"
+)
+
+valid_backends=(
+  "k3d"
+  "talos"
+)
+
+function main_check_os() {
   if [[ "$OSTYPE" != "darwin"* && "$OSTYPE" != "linux-gnu"* ]]; then
     echo "🚫 Unsupported OS. KSail only supports Unix and Linux based operating systems. Exiting..."
     exit 1
   fi
 }
 
-function define_colors() {
+function main_define_colors() {
   RED='\033[1;31m'
   GREEN='\033[1;32m'
   YELLOW='\033[1;33m'
@@ -15,87 +26,116 @@ function define_colors() {
   WHITE='\033[0m'
 }
 
-function define_font_types() {
+function main_define_font_types() {
   NORMAL=$(tput sgr0)
   BOLD=$(tput bold)
   ITALIC=$(tput sitm)
   UNDERLINE=$(tput smul)
 }
 
-function help_no_arg() {
+function main_run_global_flags() {
+  local flag=$1
+  local arg=$2
+  case "${flag}" in
+  h)
+    main_run_help "$arg"
+    exit
+    ;;
+  v)
+    main_run_version
+    exit
+    ;;
+  \?)
+    echo "🚨 Unknown flag: $1"
+    exit 1
+    ;;
+  esac
+}
+
+function main_run_help_no_arg() {
   echo "Usage:"
-  echo "  ksail [COMMAND] [FLAGS]"
+  echo -e "  ksail ${PURPLE}<command>${WHITE} [flags]"
   echo
   echo "Commands:"
   echo "  install    install dependencies"
   echo "  up         create cluster"
   echo "  down       destroy cluster"
-  echo "  validate   validate cluster manifest files"
-  echo "  verify     verify cluster reconciliation"
   echo
   echo "Global Flags:"
-  echo "  -h, --help      print help information"
-  echo "  -v, --version   print version information"
+  echo "  -h    print help information"
+  echo "  -v    print version information"
 }
 
-function help_up_arg() {
+function main_run_help_up_arg() {
   echo "Usage:"
-  echo "  ksail up [FLAGS]"
+  echo -e "  ksail up ${PURPLE}<backend>${WHITE} [flags]"
+  echo
+  echo "Backends:"
+  echo "  k3d    k3s-in-docker"
+  echo "  talos  talos-in-docker"
   echo
   echo "Flags:"
   echo -e "  -n   name of the cluster (${GREEN}ksail${WHITE})"
-  echo -e "  -b   k8s-in-docker backend (${GREEN}k3d${WHITE}, talos)"
   echo -e "  -m   path to the manifests files root directory (${GREEN}./k8s${WHITE})"
   echo -e "  -f   path to the flux kustomization manifests (${GREEN}./k8s/clusters/${PURPLE}<cluster-name>${GREEN}/flux${WHITE})"
   echo
-  echo "⚠️ Warnings:"
-  echo -e "- The clusters created by KSail are not meant for production use."
+  echo "ℹ️ Notes:"
+  echo -e "  - Backends may have additional flags. Run '${BLUE}ksail up ${PURPLE}<backend>${BLUE} -h${WHITE}' for more information."
 }
 
-function help_down_arg() {
+function main_run_help_up_k3d_arg() {
   echo "Usage:"
-  echo "  ksail down [FLAGS]"
+  echo " ksail up k3d [flags]"
+  echo
+  echo "Flags:"
+  echo -e "  -n   name of the cluster (${GREEN}ksail${WHITE})"
+  echo -e "  -m   path to the manifests files root directory (${GREEN}./k8s${WHITE})"
+  echo -e "  -f   path to the flux kustomization manifests (${GREEN}./k8s/clusters/${PURPLE}<cluster-name>${GREEN}/flux${WHITE})"
+  echo -e "  -c   path to the k3d cluster config file (${GREEN}./${PURPLE}<cluster-name>${GREEN}-k3d-config.yaml${WHITE})"
+}
+
+function main_run_help_up_talos_arg() {
+  echo "Usage:"
+  echo " ksail up talos [flags]"
+  echo
+  echo "Flags:"
+  echo -e "  -n   name of the cluster (${GREEN}ksail${WHITE})"
+  echo -e "  -m   path to the manifests files root directory (${GREEN}./k8s${WHITE})"
+  echo -e "  -f   path to the flux kustomization manifests (${GREEN}./k8s/clusters/${PURPLE}<cluster-name>${GREEN}/flux${WHITE})"
+}
+
+function main_run_help_down_arg() {
+  echo "Usage:"
+  echo -e "  ksail down ${PURPLE}<backend>${WHITE} [flags]"
+  echo
+  echo "Backends:"
+  echo "  k3d    k3s-in-docker"
+  echo "  talos  talos-in-docker"
   echo
   echo "Flags:"
   echo -e "  -n, --name      name of the cluster (${GREEN}ksail${WHITE})"
-  echo -e "  -b, --backend   k8s-in-docker backend (talos)"
 }
 
-function help_validate_arg() {
-  echo "Usage:"
-  echo "  ksail validate [FLAGS]"
-  echo
-  echo "Flags:"
-  echo "  -h, --help  # Print help information"
-}
-
-function help_verify_arg() {
-  echo "Usage:"
-  echo "  ksail verify [FLAGS]"
-  echo
-  echo "Flags:"
-  echo "  -h, --help  # Print help information"
-}
-function help() {
+function main_run_help() {
   if [ -z "${1}" ]; then
-    help_no_arg
+    main_run_help_no_arg
   else
     while [ $# -gt 0 ]; do
       case "$1" in
       up)
-        help_up_arg "$@"
+        main_run_help_up_arg "$@"
+        exit
+        ;;
+      up-k3d)
+        main_run_help_up_k3d_arg "$@"
+        exit
+        ;;
+      up-talos)
+        main_run_help_up_talos_arg "$@"
         exit
         ;;
       down)
-        help_down_arg "$@"
-        exit
-        ;;
-      validate)
-        help_validate_arg "$@"
-        exit
-        ;;
-      verify)
-        help_verify_arg "$@"
+        main_run_help_down_arg "$@"
         exit
         ;;
       *)
@@ -107,11 +147,11 @@ function help() {
   fi
 }
 
-function version() {
+function main_run_version() {
   echo "KSail $VERSION"
 }
 
-function destroy_k3d_cluster() {
+function main_run_down_destroy_k3d_cluster() {
   local cluster_name=${1}
   k3d cluster delete "$cluster_name" || {
     echo "🚨 Cluster deletion failed. Exiting..."
@@ -119,7 +159,7 @@ function destroy_k3d_cluster() {
   }
 }
 
-function destroy_talos_cluster() {
+function main_run_down_destroy_talos_cluster() {
   talosctl cluster destroy --name "${cluster_name}" --force
   talosctl config context default
   talosctl config remove "${cluster_name}" -y
@@ -132,21 +172,6 @@ function destroy_talos_cluster() {
   fi
   if kubectl config get-users | grep admin@"${cluster_name}"; then
     kubectl config delete-user admin@"${cluster_name}"
-  fi
-}
-
-function destroy_cluster() {
-  local cluster_name=${1}
-  local backend=${2}
-
-  echo "🔥 Delete ${cluster_name} cluster"
-  if [[ "$backend" == "k3d" ]]; then
-    destroy_k3d_cluster "$cluster_name"
-  elif [[ "$backend" == "talos" ]]; then
-    destroy_talos_cluster "$cluster_name"
-  else
-    echo "🚫 Unsupported backend. Exiting..."
-    exit 1
   fi
 }
 
@@ -177,13 +202,13 @@ function introduction() {
   echo
 }
 
-function run_no_arg() {
+function main_run_no_arg() {
 
   introduction
-  help
+  main_run_help
 }
 
-function run_install() {
+function main_run_install() {
   echo "📦 Installing dependencies"
   if command -v brew &>/dev/null; then
     echo "📦✅ Homebrew already installed. Updating..."
@@ -194,7 +219,7 @@ function run_install() {
     (
       echo
       echo "eval '$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)'"
-    ) >>/home/runner/.bashrc
+    ) >>/home/main_runner/.bashrc
     eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
     echo "📦✅ Homebrew installed"
   fi
@@ -472,14 +497,22 @@ function install_flux() {
   }
 }
 
-function provision_k3d_cluster() {
-  k3d cluster create --config "${cluster_name}"-k3d-config.yaml || {
-    echo "🚨 Cluster creation failed. Exiting..."
-    exit 1
-  }
+function main_run_up_provision_k3d_cluster() {
+  if $k3d_config_path; then
+    echo "⛴️ Provision ${cluster_name} cluster"
+    k3d cluster create --config "${k3d_config_path}" || {
+      echo "🚨 Cluster creation failed. Exiting..."
+      exit 1
+    }
+  else
+    k3d cluster create "$cluster_name" || {
+      echo "🚨 Cluster creation failed. Exiting..."
+      exit 1
+    }
+  fi
 }
 
-function provision_talos_cluster() {
+function main_run_up_provision_talos_cluster() {
   local cluster_name=${1}
   local docker_gateway_ip
   docker_gateway_ip=$(docker network inspect bridge --format='{{(index .IPAM.Config 0).Gateway}}')
@@ -508,54 +541,13 @@ function provision_talos_cluster() {
   # TODO: Add support for Talos patching
 }
 
-function provision_cluster() {
-  local cluster_name=${1}
-  local backend=${2}
-  local flux_path=${3}
-
-  if [[ "$backend" == "k3d" ]]; then
-    provision_k3d_cluster "$cluster_name"
-  elif [[ "$backend" == "talos" ]]; then
-    provision_talos_cluster "$cluster_name"
-  else
-    echo "🚫 Unsupported backend. Exiting..."
-    exit 1
-  fi
-  add_sops_gpg_key || {
-    echo "🚨 SOPS GPG key creation failed. Exiting..."
-    exit 1
-  }
-  install_flux "$cluster_name" "$docker_gateway_ip" "$flux_path" || {
-    echo "🚨 Flux installation failed. Exiting..."
-    exit 1
-  }
-  echo
-}
-
-function configure_up_with_prompts() {
+function main_run_up_configure_cluster_with_prompts() {
   echo -e "${BOLD}What would you like to name your cluster? (default: ${GREEN}ksail${WHITE})${NORMAL}"
   read -r cluster_name
   if [ -z "$cluster_name" ]; then
     cluster_name="ksail"
   fi
   echo
-
-  echo -e "${BOLD}What backend would you like to use?${NORMAL}"
-  PS3="Your selection: "
-  options=("talos")
-  select opt in "${options[@]}"; do
-    case $opt in
-    "talos")
-      backend="talos"
-      break
-      ;;
-    *)
-      echo "🚫 Invalid option: $REPLY."
-      echo "   You must type the number of the option you want to select."
-      echo
-      ;;
-    esac
-  done
 
   echo -e "${BOLD}What is the path to your manifests files root directory? (default: ${GREEN}./k8s${WHITE})${NORMAL}"
   read -r manifests_path
@@ -570,23 +562,12 @@ function configure_up_with_prompts() {
   fi
 }
 
-function configure_up_with_flags() {
-  if [[ "$2" != "-"* ]]; then
-    echo "🚫 Unknown flag: $2"
-    exit 1
-  fi
+function main_run_up_configure_cluster_with_flags() {
   local OPTIND=2
-  while getopts "hn:b:m:f:" flag; do
+  while getopts "n:m:f:" flag; do
     case "${flag}" in
-    h)
-      help up
-      exit
-      ;;
     n)
       cluster_name=${OPTARG}
-      ;;
-    b)
-      backend=${OPTARG}
       ;;
     m)
       manifests_path=${OPTARG}
@@ -602,23 +583,100 @@ function configure_up_with_flags() {
   done
 }
 
-function run_up() {
+function main_run_up_configure() {
+  if [ $# -eq 2 ]; then
+    main_run_up_configure_cluster_with_prompts
+  else
+    main_run_up_configure_cluster_with_flags "$@"
+  fi
+}
+
+function main_run_up_configure_k3d_cluster_with_prompts() {
+  echo -e "${BOLD}What is the path to your k3d cluster config file? (default: ${GREEN}./${cluster_name}-k3d-config.yaml${WHITE})${NORMAL}"
+  read -r k3d_config_path
+  if [ -z "$k3d_config_path" ]; then
+    k3d_config_path="./${cluster_name}-k3d-config.yaml"
+  fi
+}
+
+function main_run_up_configure_k3d_cluster_with_flags() {
+  local OPTIND=3
+  while getopts "chv" flag; do
+    case "${flag}" in
+    c)
+      k3d_config_path=${OPTARG}
+      ;;
+    *)
+      main_run_global_flags "$flag" up-k3d
+      ;;
+    esac
+  done
+}
+
+function main_run_up_configure_k3d_cluster() {
+  if [ $# -eq 2 ]; then
+    main_run_up_configure_k3d_cluster_with_prompts
+  else
+    main_run_up_configure_k3d_cluster_with_flags "$@"
+  fi
+}
+
+function main_run_up_configure_talos_cluster_with_prompts() {
+  echo
+}
+
+function main_run_up_configure_talos_cluster_with_flags() {
+  local OPTIND=3
+  while getopts "hv" flag; do
+    case "${flag}" in
+    *)
+      main_run_global_flags "$flag" up-talos
+      ;;
+    esac
+  done
+}
+
+function main_run_up_configure_talos_cluster() {
+  if [ $# -eq 2 ]; then
+    main_run_up_configure_talos_cluster_with_prompts
+  else
+    main_run_up_configure_talos_cluster_with_flags "$@"
+  fi
+}
+
+function main_run_up() {
   local cluster_name="ksail"
-  local backend="k3d"
   local manifests_path="./k8s"
   local flux_path="./k8s/clusters/${cluster_name}/flux"
-
   if [ -z "$2" ]; then
-    configure_up_with_prompts
+    main_run_help up
+  elif [[ ! " ${valid_backends[*]} " =~ (^| )${2}( |$) ]] && [[ ! " ${valid_global_flags[*]} " =~ (^| )${2}( |$) ]]; then
+    echo "🚨 Invalid argument or flag: $2"
+    exit 1
+  elif [[ " ${valid_global_flags[*]} " =~ (^| )${2}( |$) ]]; then
+    local OPTIND=2
+    while getopts "hv" flag; do
+      main_run_global_flags "$flag" up
+    done
   else
-    configure_up_with_flags "$@"
+    local backend=${2}
+    main_run_up_configure "$@"
+    if [[ "$backend" == "k3d" ]]; then
+      main_run_up_configure_k3d_cluster "$@"
+    elif [[ "$backend" == "talos" ]]; then
+      main_run_up_configure_talos_cluster "$@"
+    fi
+    check_if_docker_is_running && echo
+    create_oci_registries && echo
+    update_cluster "$cluster_name" "$manifests_path" && echo
+    if [[ "$backend" == "k3d" ]]; then
+      main_run_down_destroy_k3d_cluster "$cluster_name"
+      main_run_up_provision_k3d_cluster "$cluster_name"
+    elif [[ "$backend" == "talos" ]]; then
+      main_run_down_destroy_talos_cluster "$cluster_name"
+      main_run_up_provision_talos_cluster "$cluster_name"
+    fi
   fi
-
-  check_if_docker_is_running && echo
-  create_oci_registries && echo
-  update_cluster "$cluster_name" "$manifests_path" && echo
-  destroy_cluster "$cluster_name" "$backend" && echo
-  provision_cluster "$cluster_name" "$backend" "$flux_path"
 }
 
 function configure_down_with_prompts() {
@@ -633,23 +691,6 @@ function configure_down_with_prompts() {
     fi
   done
   echo
-
-  echo -e "${BOLD}What backend does the cluster use?${NORMAL}"
-  PS3="Your selection: "
-  options=("talos")
-  select opt in "${options[@]}"; do
-    case $opt in
-    "talos")
-      backend="talos"
-      break
-      ;;
-    *)
-      echo "🚫 Invalid option: $REPLY."
-      echo "   You must type the number of the option you want to select."
-      echo
-      ;;
-    esac
-  done
 }
 
 function configure_down_with_flags() {
@@ -657,14 +698,11 @@ function configure_down_with_flags() {
   while getopts ":hn:b:p:" flag; do
     case "${flag}" in
     h)
-      help down
+      main_run_help down
       exit
       ;;
     n)
       cluster_name=${OPTARG}
-      ;;
-    b)
-      backend=${OPTARG}
       ;;
     *)
       echo "🚫 Unknown flag: $2"
@@ -678,9 +716,8 @@ function configure_down_with_flags() {
   fi
 }
 
-function run_down() {
+function main_run_down() {
   local cluster_name="ksail"
-  local backend="k3d"
   if [ -z "$2" ]; then
     configure_down_with_prompts
   else
@@ -688,70 +725,31 @@ function run_down() {
   fi
 
   check_if_docker_is_running
-  destroy_cluster "$cluster_name" "$backend"
+  destroy_cluster "$cluster_name"
 }
 
-function run_validate() {
-  echo "validate"
-}
-
-function run_verify() {
-  echo "verify"
-}
-
-function run_args() {
-  if [[ "$1" != "-"* ]]; then
-    echo "🚫 Unknown flag: $1"
-    exit 1
-  fi
-  while getopts ":hv" flag; do
-    case "${flag}" in
-    h)
-      help
-      ;;
-    v)
-      version
-      ;;
-    \?)
-      echo "🚫 Unknown flag: $1"
-      exit 1
-      ;;
-    *)
-      shift
-      ;;
-    esac
-  done
-}
-
-function run() {
+function main_run() {
   if [ $# -eq 0 ]; then
-    run_no_arg
+    main_run_no_arg
   else
     while [ $# -gt 0 ]; do
       case "$1" in
       install)
-        run_install
+        main_run_install
         exit
         ;;
       up)
-        run_up "$@"
+        main_run_up "$@"
         exit
         ;;
       down)
-        run_down "$@"
-        exit
-        ;;
-      validate)
-        run_validate "$@"
-        exit
-        ;;
-      verify)
-        run_verify "$@"
+        main_run_down "$@"
         exit
         ;;
       *)
-        run_args "$@"
-        exit
+        while getopts "hv" flag; do
+          main_run_global_flags "$flag" ""
+        done
         ;;
       esac
     done
@@ -759,11 +757,11 @@ function run() {
 }
 
 function main() {
-  check_os
-  define_colors
-  define_font_types
+  main_check_os
+  main_define_colors
+  main_define_font_types
 
-  run "$@"
+  main_run "$@"
 }
 
 VERSION="dev"
